### ISSUE TITLE
TTL games

### ISSUE THREAD

**Issue by ghost** [ajhewitt/novasaur#1]
Hi

I try to learn how to make TTL games. Do you know example games, old books or websites?

**Comment by ajhewitt** [comment]
Writing software for a TTL computer or building a game with TTL chips? The plan is to develop and support the development of games for the Novasaur, but there's still some work to do on the video modes. In the meantime you could check out some of the excellent games developed for the Gigatron - https://forum.gigatron.io/

I made a game out of just TTL chip for a high-school project many years ago (7x7 LED matrix display). I'm not sure what examples or resources are available today, but there is one project that comes to mind - https://www.youtube.com/@natethefighter/videos

In terms of a general approach to minimal TTL hardware, you should take a look at the work of Don Lancaster. Many of his books are available online - https://www.tinaja.com/ebksamp1.shtml
